-- Create Mahila Samman Rashi submissions table (run in SQL editor)
CREATE TABLE IF NOT EXISTS mahila_samman_submissions (
  id VARCHAR PRIMARY KEY DEFAULT gen_random_uuid(),
  app_user_id VARCHAR NOT NULL REFERENCES app_users(id),
  village_id VARCHAR REFERENCES villages(id),
  village_name TEXT,
  sakhi_name TEXT NOT NULL,
  mobile_number TEXT NOT NULL,
  mobile_verified BOOLEAN DEFAULT false,
  father_husband_name TEXT NOT NULL,
  aadhaar_front TEXT,
  aadhaar_back TEXT,
  ocr_aadhaar_name TEXT,
  ocr_aadhaar_number TEXT,
  ocr_aadhaar_dob TEXT,
  ocr_aadhaar_gender TEXT,
  ocr_aadhaar_address TEXT,
  aadhaar_verified_same_as_voter BOOLEAN DEFAULT false,
  ocr_voter_id TEXT,
  ocr_voter_name TEXT,
  voter_mapping_booth_id TEXT,
  voter_mapping_name TEXT,
  voter_mapping_father_name TEXT,
  voter_mapping_village_name TEXT,
  sakhi_photo TEXT,
  declaration_checked BOOLEAN DEFAULT false,
  status TEXT DEFAULT 'pending' NOT NULL,
  admin_note TEXT,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);
